defaults:
    - agent: sac

env: cheetah_run

K: 50 
use_a: 10

experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 10

device: cuda

log_frequency: 10000
log_save_tb: true

save_video: true


seed: 1

hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}